POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "indicado 3",
    "email": "indicado4@email.com",
    "referrer": "8156bd02-2bfe-4a41-95f5-3073361db1bf" 
}

###

GET http://localhost:3333/invites/e938f45c-1f35-4a92-8b0a-b46a1c9fc080

###
GET http://localhost:3333/subscribers/e938f45c-1f35-4a92-8b0a-b46a1c9fc080/ranking/clicks

###
GET http://localhost:3333/subscribers/e938f45c-1f35-4a92-8b0a-b46a1c9fc080/ranking/count

###
GET http://localhost:3333/subscribers/e938f45c-1f35-4a92-8b0a-b46a1c9fc080/ranking/position

###
GET http://localhost:3333/ranking